services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: server
    ports:
      - "3001:3001"
    depends_on:
      - mysql_db
    environment:
      SERVER_PORT: 3001
      MYSQL_HOST: mysql_db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      DB_NAME: ProjectManager
      JWT_SECRET: secret

  mysql_db:
    container_name: mysql_db
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
